# Generated by Django 4.0.2 on 2022-02-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rareuser',
            name='created_on',
        ),
    ]
