# Generated by Django 4.0.2 on 2022-02-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_remove_rareuser_active_remove_rareuser_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='ended_on',
        ),
    ]
