# Generated by Django 4.0.2 on 2022-02-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_rareuser_profile_pic'),
        ('rareapi', '0003_rareuser_profile_pic'),
    ]

    operations = [
    ]
