# Generated by Django 4.0.2 on 2022-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_rareuser_following_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
