# Generated by Django 4.0.2 on 2022-02-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0005_rareuser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
