# Generated by Django 4.0.2 on 2022-02-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0006_rareuser_profile_pic_alter_post_approved'),
        ('rareapi', '0006_reaction_alter_post_approved_postreaction'),
    ]

    operations = [
    ]
